# Generated by Django 5.1.7 on 2025-04-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
